Add DoT with systemd-ewsolved,prepare add action python and more little changes

diff --git a/.github/workflows/ipdeny-22.04.yml b/.github/workflows/ipdeny-22.04.yml
--- a/.github/workflows/ipdeny-22.04.yml
+++ b/.github/workflows/ipdeny-22.04.yml
@@ -14,35 +14,82 @@ jobs:
   # The "build" workflow
   Creating_list:
     # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v4
 
+    - name: Settings DoT DNS with systemd-resolved
+      run: |
+       sudo apt update
+       sudo apt install -y bind9-dnsutils sudo --no-install-suggests
+       sudo mkdir -pv /etc/systemd/resolved.conf.d/
+       echo -e "[Resolve]\nDNS=8.8.4.4#dns.google\nFallbackDNS=\nDNSOverTLS=yes\nDNSSEC=yes\nCache=no\nCacheFromLocalhost=no\nReadEtcHosts=no" | sudo tee /etc/systemd/resolved.conf.d/google.conf &>/dev/null;
+       echo -e "[Resolve]\nDNS=1.0.0.1#1dot1dot1dot1.cloudflare-dns.com\nFallbackDNS=\nDNSOverTLS=yes\nDNSSEC=yes\nCache=no\nCacheFromLocalhost=no\nReadEtcHosts=no" | sudo tee /etc/systemd/resolved.conf.d/cloudflare.conf &>/dev/null;
+       cat /etc/systemd/resolved.conf.d/google.conf
+       echo ""
+       cat /etc/systemd/resolved.conf.d/cloudflare.conf
+       echo ""
+       echo "nameserver 127.0.0.53" | sudo tee /etc/resolv.conf.DNSoverride &>/dev/null;
+       sudo ln -svf /etc/resolv.conf.DNSoverride /etc/resolv.conf
+       cat -n /etc/resolv.conf
+       echo ""
+       cat -n /etc/hosts
+       echo ""
+       sudo systemctl restart systemd-resolved.service
+       nc -z -v 127.0.0.53 53 && echo ""
+
+    - name: Test DNS-query
+      run: |
+       nslookup -type=A google.com
+       echo ""
+       dig google.com A
+
     - name: Install dependencies for start script
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
-       sudo apt update
-       sudo apt install -y bind9-dnsutils git bash coreutils util-linux ccache dos2unix sudo language-pack-ru language-pack-en locales moreutils --no-install-suggests
+       sudo apt install -y git bash coreutils util-linux ccache dos2unix sudo language-pack-ru language-pack-en locales moreutils --no-install-suggests
        sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
-       sudo sed -i -e 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen
-       sudo locale-gen --no-purge en_US.UTF-8 ru_RU.UTF-8
-       sudo apt install -y ipset ipset-persistent iptables iptables-persistent wget curl grepcidr python3-netaddr python-is-python3 parallel diffutils busybox-static xterm --no-install-suggests
+       sudo sed -i -e 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen && \
+       sudo locale-gen --no-purge en_US.UTF-8 ru_RU.UTF-8 && \
+       sudo apt install -y ipset ipset-persistent iptables iptables-persistent wget libarchive-tools zstd zip unzip curl grepcidr parallel diffutils busybox-static xterm python3-netaddr python-is-python3 --no-install-suggests && \
+       dos2unix requirements.txt
+
+#    - name: Set up Python
+#      uses: actions/setup-python@v5
+#      with:
+#          python-version: '3.12'
+
+#    - name: Cache pip
+#      uses: actions/cache@v4
+#      with:
+#          path: ~/.cache/pip
+#          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
+#          restore-keys: |
+#            ${{ runner.os }}-pip-
+#            ${{ runner.os }}-
+
+ #   - name: Install dependencies
+ #     run: |
+ #         pip install -r requirements.txt
 
     - shell: bash
       env:
         TOKEN: ${{ secrets.PERSONAL_TOKEN }}
         URL: ${{ secrets.URL_PRIVATE }}
       run: |
-        curl --max-time 120 --retry-delay 3 --retry 10 -4s -H "Authorization: token ${TOKEN}" -# ${URL} | tee /tmp/ipdeny-update.sh &>/dev/null
+        curl --max-time 120 --retry-delay 3 --retry 10 -4s -H "Authorization: token ${TOKEN}" -# ${URL} | tee ./ipdeny-update.sh &>/dev/null
 
     - name: Pre-start and start bash script
+      env:
+        PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin
       run: |
-        chmod -c 755 /tmp/ipdeny-update.sh && sudo env WORKFLOW=yes /tmp/ipdeny-update.sh && \
-        cp -vf /etc/iptables/ipsets ./ipset.conf
+        chmod -c 755 ipdeny-update.sh && sudo WORKFLOW=yes ipdeny-update.sh && \
+        cp -vf /etc/iptables/ipsets ./ipset.conf && \
+        dos2unix ./ipset.conf
 
     - name: Create for Mat1RX ipset.conf
       run: |
@@ -59,8 +106,19 @@ jobs:
           sudo ipset save | sudo tee /etc/iptables/ipsets &>/dev/null
           sudo systemctl restart ipset.service
           cp -vf /etc/iptables/ipsets ./ipset_Mat1RX.conf
+          dos2unix ./ipset_Mat1RX.conf
         fi
         fi
+
+    - name: Check pre-commit ipset.conf
+      run: |
+        if [[ -s ./ipset.conf ]]; then
+          echo -e "\e[1;33mNo empty ipset.conf...\033[0m"
+          else
+          echo "Empty... Error. Exit"
+          exit 1
+        fi
+  
     - uses: stefanzweifel/git-auto-commit-action@v5
       with:
           commit_message: "Auto-update ipset.conf"
@@ -70,6 +128,16 @@ jobs:
           commit_user_name: github-actions[bot]
           commit_user_email: github-actions[bot]@users.noreply.github.com
           commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
+    
+    - name: Check pre-commit ipset_Mat1RX.conf
+      run: |
+        if [[ -s ./ipset.conf ]]; then
+          echo -e "\e[1;33mNo empty ipset_Mat1RX.conf...\033[0m"
+          else
+          echo "Empty... Error. Exit"
+          exit 1
+        fi
+
     - uses: stefanzweifel/git-auto-commit-action@v5
       with:
           commit_message: "Auto-update ipset_Mat1RX.conf for Mat1RX"
